# Enable GPU decoding
hwdec=auto-safe

# Better video scaling
profile=gpu-hq

# Keep window open at end of file
keep-open=yes

# Do not turn on the HDR in full screen
target-colorspace-hint=no

# Start in fullscreen
# fullscreen=yes

# Default volume (optional)
# volume=70
