source = $HOME/.config/hypr/themes/latte.conf

$accent = $sapphire
$accentAlpha = $sapphireAlpha
$font = JetBrainsMono Nerd Font
$monitor = DP-1

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor = DP-1
  path = $HOME/.config/hypr/wallpapers/tree/Rancho_Cucamonga_Tree_6K.png
  blur_passes = 1
  color = $base
}

background {
  monitor = HDMI-A-1
  path = $HOME/.config/hypr/wallpapers/tree/Rancho_Cucamonga_Tree_iPhone.png
  blur_passes = 1
  color = $base
}

# LAYOUT
# label {
#   monitor =
#   text = Layout: $LAYOUT
#   color = $text
#   font_size = 25
#   font_family = $font
#   position = 30, -30
#   halign = left
#   valign = top
# }

# TIME
label {
  monitor = $monitor
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = 0, -700
  halign = center
  valign = top
}

# DATE
label {
  monitor = $monitor
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = 0, -850
  halign = center
  valign = top
}

# USER AVATAR
image {
  monitor = $monitor
  path = $HOME/Dropbox/Photos/头像/2022-11-27 11.47.01.jpg
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# QUOTE
label {
  monitor = $monitor
  text = cmd[update:3600000] fortune -s
  color = $text
  font_size = 16
  font_family = $font
  position = 0, 600
  halign = center
  valign = bottom
}

# INPUT FIELD
input-field {
  monitor = DP-1
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
