wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/wallpapers/tree/Rancho_Cucamonga_Tree_6K.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpapers/tree/Rancho_Cucamonga_Tree_iPhone.png
    fit_mode = cover
}

splash = false
