# Reference: https://github.com/i3/i3/blob/next/etc/config

# Start AeroSpace at login
start-at-login = true

after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    # 'exec-and-forget sketchybar'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'


# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     0
outer.top =        [
    { monitor."built-in" = 0 },
    40
]
outer.right =      5


# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
# enable-normalization-flatten-containers = false
# enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-shift-r = 'mode resize'
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
#alt-h = 'split horizontal'
#alt-v = 'split vertical'

alt-shift-q = ['workspace 9', 'exec-and-forget open -na "Google Chrome" --args --app="https://claude.ai/new"']
alt-shift-e = ['workspace 9', 'exec-and-forget open -na "Google Chrome" --args --app="https://www.reddit.com/"']
alt-shift-x = ['workspace 9', 'exec-and-forget open -na "Google Chrome" --args --app="https://x.com/home"']
alt-shift-i = ['workspace 9', 'exec-and-forget open -na "Google Chrome" --args --app="https://instapaper.com/u"']
alt-shift-o = ['workspace 9', 'exec-and-forget open -na "Google Chrome" --args --app="https://www.xiaohongshu.com/explore"']
alt-shift-y = ['workspace 9', 'exec-and-forget open -na "Google Chrome" --args --app="https://www.youtube.com"']

alt-y = 'exec-and-forget open -na "Ghostty" --args -e btop'

alt-shift-c = 'close'
alt-shift-m = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'exec-and-forget open -na "Ghostty" --args -e yazi'


alt-shift-t = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 0'

ctrl-alt-h = 'focus-monitor left'
ctrl-alt-l= 'focus-monitor right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

[mode.resize.binding]
h = 'resize width +50'
j = 'resize height -50'
k = 'resize height +50'
l = 'resize width -50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
0 = 'main'
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'


# Picture in Picture mode
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Picture-in-picture'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
if.window-title-regex-substring = 'Picture-in-picture'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
if.window-title-regex-substring = 'Picture-in-picture'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.window-title-regex-substring = 'Picture-in-picture'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = '^about:blank$'
run = 'layout floating'
check-further-callbacks = true
# End Picture in Picture mode


# Floating windows
[[on-window-detected]]
if.app-id = 'com.colliderli.iina'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.daisydiskapp.DaisyDiskStandAlone'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.crossutility.quantumult-x'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.vinx2.vintrace'
run = 'layout floating'
check-further-callbacks = true

# Workspace allocations

# workspace 0
## Chrome apps: Excalidraw
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.kmcnjdcipmgchfndpapkoecbidofdpbc'
run = 'move-node-to-workspace 0'

# workspace 1
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 1'

# workspace 2
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 2'

# workspace 3
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 3'

# workspace 4, 5, free estate for any apps

# workspace 6 for any work related apps
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.guidedways.TodoMac'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.kjgfgldnnfoeklkmfkjfagphfepbbdan'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.flexibits.fantastical2.mac'
run = 'move-node-to-workspace 6'

# workspace 7 for notes
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 8'
