--ozone-platform=wayland
--enable-features=WaylandWindowDecorations
--enable-features=UseOzonePlatform
--disable-features=WaylandFractionalScaleV1
--enable-wayland-ime
--gtk-version=4
--password-store=basic
--enable-parallel-downloading
--process-per-site
